[prune]
  go-tests = true
  unused-packages = true
  non-go = true

#[[constraint]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "~0.18.0"

[[constraint]]
  branch = "master"
  name = "github.com/containerum/solutions"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  revision = "8152e7eb6ccf8679a64582a66b78519688d156ad"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/vbauerster/mpb"
  version = "3.2.0"
